### ISSUE TITLE
VCTK Multi Speaker Models Training Results (How many steps required for results like Pretrained)?

### ISSUE THREAD

**Issue by athenasaurav** [jaywalnut310/vits#109]
Hello Everyone,

I'm training a VCTK dataset (22050 sampling rate), downloaded, for the multi-Speaker model. I have trained for 350000 steps and yet the quality of synthesis is not good as pre-trained models in the repo. How many steps will get a similar result?

Dataset was resampled by me from 48000 to 22050.

Dataset Source : https://www.kaggle.com/datasets/showmik50/vctk-dataset

**Comment by athenasaurav** [comment]
One update, I noticed that in my dataset, there is initial silence in most of the audio files (before getting downsampled), so it remains in 22050Hz data as well.

I have used ```set_frame_rate``` function ```from pydub import AudioSegment``` to downsample the audio files only but didn't use librosa to trim silence. Is it necessary to trim silence at the start and end of every file for better results?

**Comment by athenasaurav** [comment]
Batch size 64, Steps 270000 worked for me. Good Audio Quality of the dataset is a must to have while training.

**Comment by LanglyAdrian** [comment]
"Good Audio Quality of the dataset is a must to have while training." Are you talking about your own dataset or vctk-corpus? If the answer is vctk-corpus, then what other steps did you take to improve the quality (besides removing the silence)?

**Comment by adrian585** [comment]
Hi, @athenasaurav.
I tried to train the model on the VSTK dataset, and got a good result, but there are problems with the pronunciation of one word. This problem is not only mine. Reading the comments [here](https://github.com/jaywalnut310/vits/issues/31), I got the impression that this is due to the fact that I changed the size of the batch size. With size 64, my PC can't handle it. Can you tell me what video card you used, what VRAM and RAM you have?

**Comment by athenasaurav** [comment]
Hello @adrian585 

I had used 2 GPU V100 and i also had an issue when i changed the batch size from 16 to 64, not in training but speaking the proper words. So i stick to 16 only.

**Comment by LanglyAdrian** [comment]
@athenasaurav Thank you. There is 1 more question. At the beginning, you wrote that after 350,000 the quality was poor. Also, you pointed out that you didn't remove the silence and asked if it was necessary, then wrote that you got an excellent result after 270,000 steps. Q: did you remove the silence? If not, then what exactly did you do to solve the problem? Thank you in advance
