### ISSUE TITLE
some advice about MAS Algorithm

### ISSUE THREAD

**Issue by BridgetteSong** [jaywalnut310/vits#12]
As the GlowTTS MAS definition:
![MAS](https://user-images.githubusercontent.com/12581338/123062029-c00bed00-d43e-11eb-98f9-58b399aea1ac.PNG)

to satisfy monotonicity and surjection, if **z_j** and **{u_i, σ_i}** are aligned, the previous latent variable **z_j-1** should have been aligned to
either **{u_i-1, σ_i-1}** or **{u_i, σ_i}**, which is equal to the **Forward Attention** for Tacotron2(https://arxiv.org/abs/1807.06736), my question is:

1.  replacing **max(Q_i-1_j-1, Q_i_j-1)** with **log(exp(Q_i-1_j-1) + exp(Q_i_j-1))** is a better choice?

**Comment by BridgetteSong** [comment]
I will do ablation experiments and post my results.

**Comment by BridgetteSong** [comment]
I do the ablation experiments using same Chinses dataset for MAS Algorithm.

1.  from the tensorboard, the two Algorithms have the same total loss in the same training step
2. But My MAS has the smaller Mel_Loss about 0.2

**official tensorboard**:
![1](https://user-images.githubusercontent.com/12581338/125017753-5d555b00-e0a6-11eb-83a4-c829f7f5d3c1.PNG)

**My tensorboard**:
![2](https://user-images.githubusercontent.com/12581338/125017826-7a8a2980-e0a6-11eb-837e-0768e0ded7de.PNG)


**Chinese demo:**
**official**:
[1.zip](https://github.com/jaywalnut310/vits/files/6788433/1.zip)
**My**:
[2.zip](https://github.com/jaywalnut310/vits/files/6788434/2.zip)

**Comment by BridgetteSong** [comment]
So my question is:

1. MAS is a hard attention as its attention matrix contents are one-hot vectors, so can **changing a soft attention** improve audio quality? such as in **EATS** or **Non-Attentive Tacotron** or **Parallel Tacotron2**.(I will try next)
2.  MAS Backtracking is a CPU dp search to maintain Monotonicity, so using a GPU argmax to get duration and using monotonic attention  constraint in attention loss such as Guided Attention Loss can improve quality (like **BVAE**)?(I will try next)

**Comment by xiaoyangnihao** [comment]
> I will do ablation experiments and post my results.

@BridgetteSong  Hi，how about your ablation experiments and results?

**Comment by BridgetteSong** [comment]
@ [xiaoyangnihao](https://github.com/xiaoyangnihao)
1. there are some bugs in new MAS, I need time to fix bugs, but I don't much time to do this.
2. I emailed to the author to discuss the MAS. Now I think a soft alignment is key to improve quality, and my method maybe only improves stability. But author's MAS is stable enough, so I don't experiment more.
