### ISSUE TITLE
How many training epochs are required to hear the content of synthetic speech clearly?

### ISSUE THREAD

**Issue by GoArsenal** [jaywalnut310/vits#128]
\# utterance = 10000
\# batch size = 16

**Comment by SODAsoo07** [comment]
As of batch size 12, not included silence utterance sample 42min, I was get to clear results in steps 4 epoch, 330K Step.

**Comment by LanglyAdrian** [comment]
@SODAsoo07, hi!
Have you trained on the VCTK dataset? Can you try generating a wav for "capital" (any voice)? Was the result good? Sounds out the whole word?
