### ISSUE TITLE
Is it possible to manually condition  pitch and duration like FastPitch ?

### ISSUE THREAD

**Issue by jmasterx** [jaywalnut310/vits#16]
Hello,

Thank you for sharing this great work!

I had a look at the model. There seems to be a duration predictor but I do not see a way to provide input pitch conditioning.

Is this possible? If not do you think it would be trivial to add support for pitch conditioning?

**Comment by JohnHerry** [comment]
> Hello,
> 
> Thank you for sharing this great work!
> 
> I had a look at the model. There seems to be a duration predictor but I do not see a way to provide input pitch conditioning.
> 
> Is this possible? If not do you think it would be trivial to add support for pitch conditioning?

The vits posterior take the role to encode audios into lattent representaion, the "z",  all audio features- include the pitch, are contained in those "z" tensors. so it is no need to make the pitch be a teacher to help training the waveform generation.
