### ISSUE TITLE
How to use ground truth durations to train vits?

### ISSUE THREAD

**Issue by 16dian11** [jaywalnut310/vits#170]
I have a ground truth duration and would like to use it for training vits. How can I modify the code?

**Comment by p0p4k** [comment]
convert these seconds to spectrogram frame timing (integers; by ceiling). I think it is `frame numbers = ((total number of samples - win_size) / hop_size) + 1`.
`total number of samples = seconds * sample_rate`

**Comment by 16dian11** [comment]
> convert these seconds to spectrogram frame timing (integers; by ceiling). I think it is `frame numbers = ((total number of samples - win_size) / hop_size) + 1`. `total number of samples = seconds * sample_rate`
Thank you for your reply. In fact, I have the duration of each phoneme, but I don't know how to use it to modify the duration predictor section.

**Comment by 16dian11** [comment]
Thank you for your reply. In fact, I have the duration of each phoneme, but I don't know how to use it to modify the duration predictor section.

**Comment by p0p4k** [comment]
This might help https://github.com/heatz123/naturalspeech/blob/main/models/models.py#L586

**Comment by 16dian11** [comment]
> This might help https://github.com/heatz123/naturalspeech/blob/main/models/models.py#L586


This really helped me a lot, thank you very much！！！

**Comment by phamkhactu** [comment]
> I have a ground truth duration and would like to use it for training vits. How can I modify the code?


Hi @16dian11
what is the ground truth duration? It means that it a time interval for each phone, it is right?
if I am wrong, I am very happy whether you give me more detail info.

Thank you
