### ISSUE TITLE
Mispronunciation and what is the purpose of the add_blank config ?

### ISSUE THREAD

**Issue by leminhnguyen** [jaywalnut310/vits#20]
I've trained my own dataset with the default config except for `add_blank` option (I changed it to `false`). I know the `add_blank` option will add the 0 between the symbol ids but in my case it's been disabled. And I trained with phonemes and got 200K steps right now, but some phonemes seem to be spelled wrong. So I have some question ?

1. What is the purpose of the add_blank config ?
2. The reason for model to spell wrong ? How can I improve my model with the pronunciation ?

**Comment by BillyBobQuebec** [comment]
perhaps they are connected? I believe the purpose of the add_blank is to improve stability in the model, try retraining with add_blank and see if your pronunciation issues are fixed.

**Comment by nikich340** [comment]
Did `add_blank` help anyhow?

**Comment by candlewill** [comment]
In my experiment on the Chinese dataset, it would lead to serious speech quality degradation and mispronunciations if set `add_blank=False`.  

Here are some samples:
[add_blank=False samples.zip](https://github.com/jaywalnut310/vits/files/8486114/add_blank.False.samples.zip)


Instead of that, the speech is pretty good when set `add_blank=True`.

**Comment by yinhao0214** [comment]
> In my experiment on the Chinese dataset, it would lead to serious speech quality degradation and mispronunciations if set `add_blank=False`.
> 
> Here are some samples: [add_blank=False samples.zip](https://github.com/jaywalnut310/vits/files/8486114/add_blank.False.samples.zip)
> 
> Instead of that, the speech is pretty good when set `add_blank=True`.

can you share your good synthetic wav with add_blank=True for chinese.

**Comment by JohnHerry** [comment]
> In my experiment on the Chinese dataset, it would lead to serious speech quality degradation and mispronunciations if set `add_blank=False`.
> 
> Here are some samples: [add_blank=False samples.zip](https://github.com/jaywalnut310/vits/files/8486114/add_blank.False.samples.zip)
> 
> Instead of that, the speech is pretty good when set `add_blank=True`.

There is nature blank between Chinese pinyin phonemes, though not coded as zero, Is it nesseary to add additional blank?
