### ISSUE TITLE
Continue training VITS

### ISSUE THREAD

**Issue by Pipe1213** [jaywalnut310/vits#211]
I was training my model using my own dataset, but I have had a problem and it has stopped suddenly, in previous occasions the same thing has happened to me and the training continued normally at the Epoch where it had stopped, but this time, it is starting again although it recognizes the last checkpoint (attached image), do you know what could be happening and how can I fix it?

![Screenshot 2024-05-09 181713](https://github.com/jaywalnut310/vits/assets/123564842/777cb211-82e3-44ac-870e-552fa81de0f4)

Thanks !

**Comment by Yogatiara** [comment]
what a solution?

**Comment by Pipe1213** [comment]
Be sure that you didn't change any other file, also just to be sure, try to leave a previous checkpoint, depending on how the training was stopped, the last checkpoint may have an error. Another thing that can work is just to leave the checkpoint from which you want to continue in the folder (generator and discriminator)
