### ISSUE TITLE
Flip module explain

### ISSUE THREAD

**Issue by chnk58hoang** [jaywalnut310/vits#214]
Hi. First of all, thank you for your great work. I'm reading your code and currently I'm confusing with the meaning of Flip() modules. Can you explain why we need to flip the tensor when applying flow modules. Thank you so much
![image](https://github.com/jaywalnut310/vits/assets/71833423/a0be1f8a-8c48-47cf-bc9e-319d4b0f4df2)

**Comment by FMzzq** [comment]
flow 是要用flip的啊 标准用法啊，总不能一直只要上半部分数据，要交换着来
