### ISSUE TITLE
Phonemizer is too slow

### ISSUE THREAD

**Issue by Selimonder** [jaywalnut310/vits#26]
ViTs accepts phonemized input data during training and inference. The phonemizer doesn't create a bottleneck on training because we use pre-processed data. But on inference if the model forward is taking 0.1 seconds, phonemizer is consuming minimum 0.3->0.5 seconds, so the majority of time spent on phonemizer. Do you guys have any workaround for this? Should we be training a light neural net phonemizer for this purpose?

**Comment by Selimonder** [comment]
bottleneck (see: https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/text/cleaners.py#L98).

instead

```
import phonemizer
global_phonemizer = phonemizer.backend.EspeakBackend(language='en-us', preserve_punctuation=True,  with_stress=True)

def english_cleaners2(text):
...
    phonemes = global_phonemizer.phonemize(text, strip=True, njobs=1)
...
```

would speed things up

**Comment by SeongYeonPark** [comment]
Amazing solution. Speed things up significantly.

Additionally wondering, can I get a progress bar for this?

**Comment by NikitaKononov** [comment]
> Amazing solution. Speed things up significantly.
> 
> Additionally wondering, can I get a progress bar for this?

use tqdm

**Comment by shivammehta25** [comment]
Thank you for the tip the speed up was significant, The global_phonemizer.phonemize function takes a list as an input so this should fix it! 
```python
    phonemes = global_phonemizer.phonemize([text], strip=True, njobs=1)[0]
```
