### ISSUE TITLE
espeak

### ISSUE THREAD

**Issue by AK391** [jaywalnut310/vits#3]
Hello, I am looking to make a web demo for this on gradio hub https://gradio.app/hub, could this be used instead of espeak? https://pypi.org/project/py-espeak-ng/

**Comment by AK391** [comment]
I have added a working version from colab here https://github.com/AK391/vits looking to add espeak

**Comment by AK391** [comment]
@jaywalnut310 getting this error currently
<img width="592" alt="Screen Shot 2021-06-14 at 4 52 58 PM" src="https://user-images.githubusercontent.com/81195143/121957887-053e6980-cd31-11eb-99a6-5e9fe7f1155f.png">

**Comment by AK391** [comment]
note the gradio demo works in google colab

**Comment by AK391** [comment]
resolved

**Comment by kin0303** [comment]
Hi @AK391, what script do you use espeak on?

**Comment by wsywsywsywsywsy979** [comment]
> @jaywalnut310当前收到此错误 <img alt="屏幕截图 2021-06-14 在 4 52 58 PM" width="592" src="https://user-images.githubusercontent.com/81195143/121957887-053e6980-cd31-11eb-99a6-5e9fe7f1155f.png">

hello,I meet this error , could you tell me how do you solve it? Thank you!
