### ISSUE TITLE
about multi-speaker data

### ISSUE THREAD

**Issue by LH997** [jaywalnut310/vits#51]
Thanks for your great work. I want to train with my own dataset. So I want to ask what does this number '67' mean in your data? And how it is calculated.

E.g：DUMMY2/p229/p229_128.wav|67|The whole process is a vicious circle at the moment.

**Comment by MaxMax2016** [comment]
speaker id?

**Comment by LH997** [comment]
大佬，我用过您的标贝数据集那个项目，我现在想使用aishell3进行多人的训练。他这个id是根据什么标准来确定序号的啊

**Comment by MaxMax2016** [comment]
按顺序，随意取都可以，也可以用声纹编码替代

**Comment by LH997** [comment]
好的，非常感谢！
