### ISSUE TITLE
Could you please explain the KL loss in losses.py

### ISSUE THREAD

**Issue by unrea1-sama** [jaywalnut310/vits#55]
Hi, when I was reading the code, I find it hard for me to understand `kl_loss` in `losses.py`. In the paper, the KL loss includes an approximate posterior distribution q, and the Jacobian of flow. It seems that these two terms are not added to KL loss. I wonder if this is because these two terms don't contribute to parameter optimization so we don't need them in KL loss.

**Comment by AndreyBocharnikov** [comment]
Hello, KL loss was discussed [here](https://github.com/jaywalnut310/vits/issues/46) and [here](https://github.com/jaywalnut310/vits/issues/6).

**Comment by unrea1-sama** [comment]
> Hello, KL loss was discussed [here](https://github.com/jaywalnut310/vits/issues/46) and [here](https://github.com/jaywalnut310/vits/issues/6).

Thank you!
