### ISSUE TITLE
KL Loss is right?

### ISSUE THREAD

**Issue by BridgetteSong** [jaywalnut310/vits#6]
When I searched KL-divergence between two Gaussians, I got this which is diffenrent from your KL loss
https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians
![kl](https://user-images.githubusercontent.com/12581338/122048593-0d230a00-ce14-11eb-87b9-e5a108573d9f.PNG)

**Comment by jaywalnut310** [comment]
Hi @BridgetteSong. Yes, (closed-form) KL-divergence between two Gaussians is different from our KL loss. It's because we use KL-divergence between a Gaussian and a Normalizing flow rather than two Gaussians. Therefore, there is no closed-form KL like Gaussians. Equation 4 of our paper shows that the prior distribution is not Gaussian.

If you're not familiar with normalizing flows, and if you don't know how to calculate their log-likelihood (which is needed for calculating KL), it would be better to look these blog posts first: [nf1](https://blog.evjang.com/2018/01/nf1.html) and [nf2](https://blog.evjang.com/2018/01/nf2.html). These are great illustrative blog posts about normalizing flows containing model implementations.

**Comment by BridgetteSong** [comment]
Thank you for your reply.
According to my understanding, **posterior distribution** is Gaussian, and **prior distribution** is product of prior Gaussian and absolute value of the determinant (Equation 4). So KL loss is following:

```
1. q(z/x) = torch.distributions.normal.Normal(m_q, exp(logs_q))
2. p(z/c) = torch.distributions.normal.Normal(m_p, exp(logs_p)) * torch.abs(jacobian determinant)
3. kl_loss = torch.distributions.kl.kl_divergence(q(z/x), p(z/c))
```

is my understanding right? or is this kl_loss equal to your kl loss?
I will appreciate if you can give a detailed explanation.

**Comment by jaywalnut310** [comment]
@BridgetteSong You're right. the posterior is gaussian, and the prior is product of Gaussian and the jacobian determinant.

Let me explain the kl loss in detail. For brevity, and without loss of generality, I'll assume the channel dimension of latent variables is one.

The kl divergence is the mean of the difference of log probabilities as follows:
*  mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)

As q(z/x) is gaussian, we can calculate the closed form mean of log(q(z/x)), which is the negative entropy of gaussian (see https://en.wikipedia.org/wiki/Normal_distribution):
* mean of log(q(z/x)) = negative entropy of q(z|x) = -logs_q - 0.5 - 0.5 * log(2*pi)

On the other hand, the mean of log(p(z/c)) has no closed-form solution. So we have to calculate log(p(z/c)) for each sampled z and then average them out:
* log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + logdet(df/dz), where f is a normalizing flow.

As we constrain the normalizing flow of prior distribution is volume-preserving, which uses shift-only (=mean-only) operation in coupling layers, the jacobian determinant of prior is one (see https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L449 and https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L179-L209):
* log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + 0 = -logs_p - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2

Then, kl = the average of ( negative entropy of q(z/x) - log(p(z/c))) is:
* (logs_p - logs_q - 0.5) + 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2, where f(z) is z_p in our code.

This is the explanation of the kl loss (https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/losses.py#L57-L60).

**Comment by BridgetteSong** [comment]
Thank you very much for your patience and detailed answer, I got it.

**Comment by BridgetteSong** [comment]
BTW, as the prior is product of Gaussian and the jacobian determinant, and considering properties of Gaussian distribution(if X ~ N(u, σ**2), aX+b ~ N(au+b, (aσ)**2)), so the prior is always a Gaussian distribution when the jacobian determinant is a constant. So can we calculate KL-divergence using abovementioned two Gaussian KL-divergence or use torch API to get KL-divergence directly like this?
`kl_loss = torch.distributions.kl.kl_divergence(q(z/x), p(z/c))`

**Comment by jaywalnut310** [comment]
Good point! In case the channel dimension of latent variables is one, the prior is Gaussian when the jacobian determinant is a constant.
However, when the channel dimension of latent variables exceeds one, it's not true.
For example, Let (x1, x2) ~ N( (0, 0), I), then transform it into (y1, y2) = (x1, cos(x1) + x2).
Because of the non-linear transformation, the joint distribution of (y1, y2) is not Gaussian. 
However, the jacobian determinant is still one, as the first order derivatives are : dy1/dx1 = 1, dy1/dx2 = 0, dy2/dx1 = -sin(x1), dy2/dx2 = 1.

The normalizing flow of prior also provides non-linear transformation using neural-networks while maintaining a constant jacobian determinant, resulting in non-Gaussian prior distribution. If the normalizing flow of prior only allows linear transformation or the channel dimension of latent variables is one, you can use the KL-divergence btw two Gaussians. But, in general, you cannot use it.

**Comment by BridgetteSong** [comment]
Thank you very much again. I totally understand now. I learned much from your detailed answer.

**Comment by haoheliu** [comment]
Hi @jaywalnut310, thanks for your detailed answer. Very helpful! I'd like to ask two more questions. I'd appreciate it if I can have your answers.

> As we constrain the normalizing flow of prior distribution is volume-preserving, which uses shift-only (=mean-only) operation in coupling layers, the jacobian determinant of prior is one (see

You mentioned you set up the normalizing flow to be volume-preserving. Did this way benefit the model? In my understanding, it can be replaced by a more complicated non-volume-preserving flow model.

> The kl divergence is the mean of the difference of log probabilities as follows:
mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)

As far as I know, the KL divergence value lies in the range between [0,+inf]. But according to your formula, its value could be negative? (ref: https://towardsdatascience.com/light-on-math-machine-learning-intuitive-guide-to-understanding-kl-divergence-2b382ca2b2a8)

**Comment by MlWoo** [comment]
@haoheliu 
(1) I think non-volume-persering flow model is also OK. However, the determinant of prior is not one and determined by the flow and variable of the input. I GUESS it may cause instability of training although the determinant of prior could be calculated from the flow.
(2) The KL loss could be negative according to the formula because it is not a closed-form solution but the estimation from a sample rather than the expectation of the whole distribution .

**Comment by candlewill** [comment]
How about taking absolute value to overcome kl loss is negative?

```diff
--- a/losses.py
+++ b/losses.py
@@ -54,7 +54,7 @@ def kl_loss(z_p, logs_q, m_p, logs_p, z_mask):
   logs_p = logs_p.float()
   z_mask = z_mask.float()
 
-  kl = logs_p - logs_q - 0.5
+  kl = torch.abs(logs_p - logs_q - 0.5)
```

**Comment by yanggeng1995** [comment]
> @BridgetteSong You're right. the posterior is gaussian, and the prior is product of Gaussian and the jacobian determinant.
> 
> Let me explain the kl loss in detail. For brevity, and without loss of generality, I'll assume the channel dimension of latent variables is one.
> 
> The kl divergence is the mean of the difference of log probabilities as follows:
> 
> * mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)
> 
> As q(z/x) is gaussian, we can calculate the closed form mean of log(q(z/x)), which is the negative entropy of gaussian (see https://en.wikipedia.org/wiki/Normal_distribution):
> 
> * mean of log(q(z/x)) = negative entropy of q(z|x) = -logs_q - 0.5 - 0.5 * log(2*pi)
> 
> On the other hand, the mean of log(p(z/c)) has no closed-form solution. So we have to calculate log(p(z/c)) for each sampled z and then average them out:
> 
> * log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + logdet(df/dz), where f is a normalizing flow.
> 
> As we constrain the normalizing flow of prior distribution is volume-preserving, which uses shift-only (=mean-only) operation in coupling layers, the jacobian determinant of prior is one (see
> 
> https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L449
> 
> and
> https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L179-L209
> 
> ):
> * log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + 0 = -logs_p - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2
> 
> Then, kl = the average of ( negative entropy of q(z/x) - log(p(z/c))) is:
> 
> * (logs_p - logs_q - 0.5) + 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2, where f(z) is z_p in our code.
> 
> This is the explanation of the kl loss (
> 
> https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/losses.py#L57-L60
> 
> ).

Hi，I'm a bit confused “ The kl divergence is the mean of the difference of log probabilities as follows: mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)”，doesn't the kl divergence need integration？Why do you directly kl=mean(log(q(z/x))) - mean(log(p(z/c)))

**Comment by yanggeng1995** [comment]
> @BridgetteSong You're right. the posterior is gaussian, and the prior is product of Gaussian and the jacobian determinant.
> 
> Let me explain the kl loss in detail. For brevity, and without loss of generality, I'll assume the channel dimension of latent variables is one.
> 
> The kl divergence is the mean of the difference of log probabilities as follows:
> 
> * mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)
> 
> As q(z/x) is gaussian, we can calculate the closed form mean of log(q(z/x)), which is the negative entropy of gaussian (see https://en.wikipedia.org/wiki/Normal_distribution):
> 
> * mean of log(q(z/x)) = negative entropy of q(z|x) = -logs_q - 0.5 - 0.5 * log(2*pi)
> 
> On the other hand, the mean of log(p(z/c)) has no closed-form solution. So we have to calculate log(p(z/c)) for each sampled z and then average them out:
> 
> * log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + logdet(df/dz), where f is a normalizing flow.
> 
> As we constrain the normalizing flow of prior distribution is volume-preserving, which uses shift-only (=mean-only) operation in coupling layers, the jacobian determinant of prior is one (see
> 
> https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L449
> 
> and
> https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L179-L209
> 
> ):
> * log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + 0 = -logs_p - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2
> 
> Then, kl = the average of ( negative entropy of q(z/x) - log(p(z/c))) is:
> 
> * (logs_p - logs_q - 0.5) + 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2, where f(z) is z_p in our code.
> 
> This is the explanation of the kl loss (
> 
> https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/losses.py#L57-L60
> 
> ).


Hi, I'm a bit confused “ The kl divergence is the mean of the difference of log probabilities as follows: mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)”，doesn't the kl divergence need integration？ You directly kl=mean(log(q(z/x))) - mean(log(p(z/c)))，is this an approximate formula？In this case, isn't it more convenient to calculate the negative log likelihood based on z_p obtained according to flow transformation， m_p and logs_p?

**Comment by BridgetteSong** [comment]
其实KL_loss本身是积分形式：
&nbsp; &nbsp; KL_loss = ∫q(z/x) * (log(q(z/x)) - log(p(z/c)))dx = ∫q(z/x) * log(q(z/x))dx - ∫q(z/x) * log(p(z/c)))dx
1. 因为q(z/x)是高斯分布，所以∫q(z/x) * log(q(z/x))dx可以直接计算：-logs_q - 0.5 - 0.5 * log(2*pi)
2. 而对于∫q(z/x) * log(p(z/c)))dx来说，我们无法直接计算积分形式，所以只能通过采样的方式去近似逼近：采样n个z, 然后计算mean(log(p(z/c)))。而在通常的计算中，我们都是采样一个点就够了(VAE论文中有阐述)，所以∫q(z/x) * log(p(z/c)))dx ≈ mean(log(p(z/c))) = log(p(z/c)). 

3. log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + logdet(df/dz), 由于flow是mean-only, 所以logdet(df/dz) = 0


你可以忽略作者写的kl = mean(log(q(z/x))) - mean(log(p(z/c)))，当做积分形式来理解


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "jaywalnut310/vits"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月9日(星期五) 下午3:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jaywalnut310/vits] KL Loss is right? (#6)





  
@BridgetteSong You're right. the posterior is gaussian, and the prior is product of Gaussian and the jacobian determinant.
 
Let me explain the kl loss in detail. For brevity, and without loss of generality, I'll assume the channel dimension of latent variables is one.
 
The kl divergence is the mean of the difference of log probabilities as follows:
  
mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)
  
As q(z/x) is gaussian, we can calculate the closed form mean of log(q(z/x)), which is the negative entropy of gaussian (see https://en.wikipedia.org/wiki/Normal_distribution):
  
mean of log(q(z/x)) = negative entropy of q(z|x) = -logs_q - 0.5 - 0.5 * log(2*pi)
  
On the other hand, the mean of log(p(z/c)) has no closed-form solution. So we have to calculate log(p(z/c)) for each sampled z and then average them out:
  
log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + logdet(df/dz), where f is a normalizing flow.
  
As we constrain the normalizing flow of prior distribution is volume-preserving, which uses shift-only (=mean-only) operation in coupling layers, the jacobian determinant of prior is one (see
 
https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L449
 
and
 https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L179-L209
 
):
  
log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + 0 = -logs_p - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2
  
Then, kl = the average of ( negative entropy of q(z/x) - log(p(z/c))) is:
  
(logs_p - logs_q - 0.5) + 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2, where f(z) is z_p in our code.
  
This is the explanation of the kl loss (
 
https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/losses.py#L57-L60
 
).
  
Hi, I'm a bit confused “ The kl divergence is the mean of the difference of log probabilities as follows: mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)”，doesn't the kl divergence need integration？ You directly kl=mean(log(q(z/x))) - mean(log(p(z/c)))，is this an approximate formula？In this case, isn't it more convenient to calculate the negative log likelihood based on z_p obtained according to flow transformation， m_p and logs_p?

**Comment by BridgetteSong** [comment]
> Hi, I'm a bit confused “ The kl divergence is the mean of the difference of log probabilities as follows: mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)”，doesn't the kl divergence need integration？ You directly kl=mean(log(q(z/x))) - mean(log(p(z/c)))，is this an approximate formula？In this case, isn't it more convenient to calculate the negative log likelihood based on z_p obtained according to flow transformation， m_p and logs_p?


@yanggeng1995  I will give some additional supplements:
1. _**KL_loss = ∫q(z/x) * (log(q(z/x)) - log(p(z/c)))dz = ∫q(z/x) * log(q(z/x))dz - ∫q(z/x) * log(p(z/c)))dz**_
2. as **_q(z/x)_** is gaussian, so **_∫q(z/x) * log(q(z/x))dz = -logs_q - 0.5 - 0.5 * log(2*pi)._**
3. we can't directly compute **_∫q(z/x) * log(p(z/c)))dz_**, so we only approximately compute it by sampling method. as usually, we sample some **_z_** values and average them. In the VAE code, usually sampling one **_z_** is enough, so **_∫q(z/x) * log(p(z/c)))dz ≈ mean(log(p(z/c))) = log(p(z/c))._**

**Comment by yanggeng1995** [comment]
> Thanks for your answer. There is another question, why not calculate the negative log-likelihood of Gaussian distribution based on z_p, m_p and logs_p, isn't it more convenient?

**Comment by yanggeng1995** [comment]
> > > @BridgetteSong You're right. the posterior is gaussian, and the prior is product of Gaussian and the jacobian determinant.
> > > Let me explain the kl loss in detail. For brevity, and without loss of generality, I'll assume the channel dimension of latent variables is one.
> > > The kl divergence is the mean of the difference of log probabilities as follows:
> > > 
> > > * mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)
> > > 
> > > As q(z/x) is gaussian, we can calculate the closed form mean of log(q(z/x)), which is the negative entropy of gaussian (see https://en.wikipedia.org/wiki/Normal_distribution):
> > > 
> > > * mean of log(q(z/x)) = negative entropy of q(z|x) = -logs_q - 0.5 - 0.5 * log(2*pi)
> > > 
> > > On the other hand, the mean of log(p(z/c)) has no closed-form solution. So we have to calculate log(p(z/c)) for each sampled z and then average them out:
> > > 
> > > * log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + logdet(df/dz), where f is a normalizing flow.
> > > 
> > > As we constrain the normalizing flow of prior distribution is volume-preserving, which uses shift-only (=mean-only) operation in coupling layers, the jacobian determinant of prior is one (see
> > > https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L449
> > > 
> > > and
> > > https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/models.py#L179-L209
> > > 
> > > ):
> > > 
> > > * log(p(z/c)) = log(N(f(z)|m_p, logs_p))) + 0 = -logs_p - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2
> > > 
> > > Then, kl = the average of ( negative entropy of q(z/x) - log(p(z/c))) is:
> > > 
> > > * (logs_p - logs_q - 0.5) + 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2, where f(z) is z_p in our code.
> > > 
> > > This is the explanation of the kl loss (
> > > https://github.com/jaywalnut310/vits/blob/2e561ba58618d021b5b8323d3765880f7e0ecfdb/losses.py#L57-L60
> > > 
> > > ).
> > 
> > 
> > Hi, I'm a bit confused “ The kl divergence is the mean of the difference of log probabilities as follows: mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)”，doesn't the kl divergence need integration？ You directly kl=mean(log(q(z/x))) - mean(log(p(z/c)))，is this an approximate formula？In this case, isn't it more convenient to calculate the negative log likelihood based on z_p obtained according to flow transformation， m_p and logs_p?
> 
> @yanggeng1995 I will give some additional supplements:
> 
> 1. _**KL_loss = ∫q(z/x) * (log(q(z/x)) - log(p(z/c)))dx = ∫q(z/x) * log(q(z/x))dx - ∫q(z/x) * log(p(z/c)))dx**_
> 2. as **_q(z/x)_** is gaussian, so **_∫q(z/x) * log(q(z/x))dx = -logs_q - 0.5 - 0.5 * log(2*pi)._**
> 3. we can't directly compute **_∫q(z/x) * log(p(z/c)))dx_**, so we only approximately compute it by sampling method. as usually, we sample some **_z_** values and mean of them. In the VAE code, usually sampling one **_z_** is enough, so **_∫q(z/x) * log(p(z/c)))dx ≈ mean(log(p(z/c))) = log(p(z/c))._**

@BridgetteSong Thanks for your answer. There is another question, why not calculate the negative log-likelihood of Gaussian distribution based on z_p, m_p and logs_p, isn't it more convenient?

**Comment by BridgetteSong** [comment]
@yanggeng1995 it is very convenient to compute ∫q(z/x) * log(q(z/x))dz as it is Gaussian. And as for ∫q(z/x) * log(p(z/c)))dz, it is also convenient to compute it if you understand approximate sampling: ∫q(z/x) * log(p(z/c)))dz ≈ log(p(z/c)).

p(z/c) is product of Gaussian and the jacobian determinant. To compute log(p(z/c)), we need first sample z ~ posterior(),  and get z_p = NormalizedFlow(z), finally use z_p to compute log-likelihood of prior Gaussian: N(z_p, m_p, logs_p). 

so log(p(z/c)) = logdet(df/dz) + log(N(z_p, m_p, logs_p)) = 0 - logs_p - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_p) * (f(z) - m_p) ** 2. 

I think it is also right if you directly use kl_loss ≈ log(q(z/x)) - log(p(z/c)), just log(q(z/x)) = - logs_q - 0.5 * log(2*pi) - 0.5 * exp(-2 * logs_q) * (z - m_q) ** 2 where z ~ posterior(m_q, logs_q), and log(p(z/c)) is the same. I think the author's method is more concise and more accurate.

**Comment by 980202006** [comment]
> How about taking absolute value to overcome kl loss is negative?
> 
> ```diff
> --- a/losses.py
> +++ b/losses.py
> @@ -54,7 +54,7 @@ def kl_loss(z_p, logs_q, m_p, logs_p, z_mask):
>    logs_p = logs_p.float()
>    z_mask = z_mask.float()
>  
> -  kl = logs_p - logs_q - 0.5
> +  kl = torch.abs(logs_p - logs_q - 0.5)
> ```

Hi, Is it work?

**Comment by BridgetteSong** [comment]
@980202006 It will not work. As usually, KL_loss will not be negative if your inputs and network are right. When kl_loss < 0, it means your prior distribution is almost same as posterior distribution, so posterior distribution fails to learn as a complicated distribution.
When kl_loss < 0, The first thing you should to do is checking your inputs and network. If you must add some constraints in the loss formula, you should add abs function to all items not first item like this:

- `kl = logs_p - logs_q - 0.5 `
- `kl += 0.5 * ((z_p - m_p)**2) * torch.exp(-2. * logs_p)` 
- `kl = torch.clamp(kl, min=0.0)`

But in usually, you need not add this constraint, as when your KL_Loss < 0, it means your network is trained unsuccessfully, although you add this constraint, you can't get right results.

**Comment by fenling** [comment]
> > Hi, I'm a bit confused “ The kl divergence is the mean of the difference of log probabilities as follows: mean(log(q(z/x))) - mean(log(p(z/c))), where z ~ q(z/x)”，doesn't the kl divergence need integration？ You directly kl=mean(log(q(z/x))) - mean(log(p(z/c)))，is this an approximate formula？In this case, isn't it more convenient to calculate the negative log likelihood based on z_p obtained according to flow transformation， m_p and logs_p?
> 
> @yanggeng1995 I will give some additional supplements:
> 
> 1. _**KL_loss = ∫q(z/x) * (log(q(z/x)) - log(p(z/c)))dz = ∫q(z/x) * log(q(z/x))dz - ∫q(z/x) * log(p(z/c)))dz**_
> 2. as **_q(z/x)_** is gaussian, so **_∫q(z/x) * log(q(z/x))dz = -logs_q - 0.5 - 0.5 * log(2*pi)._**
> 3. we can't directly compute **_∫q(z/x) * log(p(z/c)))dz_**, so we only approximately compute it by sampling method. as usually, we sample some **_z_** values and average them. In the VAE code, usually sampling one **_z_** is enough, so **_∫q(z/x) * log(p(z/c)))dz ≈ mean(log(p(z/c))) = log(p(z/c)).
@BridgetteSong hi，i want to know why mean(log(p(z/c))) = log(p(z/c)).sampling one z is enought,why？

**Comment by Cheneng** [comment]
> @980202006 It will not work. As usually, KL_loss will not be negative if your inputs and network are right. When kl_loss < 0, it means your prior distribution is almost same as posterior distribution, so posterior distribution fails to learn as a complicated distribution. When kl_loss < 0, The first thing you should to do is checking your inputs and network. If you must add some constraints in the loss formula, you should add abs function to all items not first item like this:
> 
> * `kl = logs_p - logs_q - 0.5 `
> * `kl += 0.5 * ((z_p - m_p)**2) * torch.exp(-2. * logs_p)`
> * `kl = torch.clamp(kl, min=0.0)`
> 
> But in usually, you need not add this constraint, as when your KL_Loss < 0, it means your network is trained unsuccessfully, although you add this constraint, you can't get right results.

A larger batch size may help : ) , I think there are some abnormal or extreme point may ruin your model. And once I enlarge my batch size, problem disappear
