### ISSUE TITLE
How to change the speaker when inferencing?

### ISSUE THREAD

**Issue by ZJ-CAI** [jaywalnut310/vits#71]
Is it valid by changing the number in the code "_sid = torch.LongTensor([4]).cuda()_"?

Thank you

**Comment by athenasaurav** [comment]
Yes, you can change the SID like that. The SID of the speaker can be get using the file list txt files. 

As for the VCTK dataset, 
```
DUMMY2/p253/p253_281.wav|70|
```
here it means the speaker "p253" has a SID of "70"
