### ISSUE TITLE
Questions about the Korean datasets

### ISSUE THREAD

**Issue by ORI-Muchim** [jaywalnut310/vits#92]
Hello, I am currently learning data in Korean. vits can't pronounce properly even though it's 100 epochs. Will the results change if I continue to learn more?

Here is my learning results.

KSS: [단순하게 살아라, 현대인은 쓸데없는 절차와 일 때문에 얼마나 복잡한 삶을 살아가는가?]
[output8.zip](https://github.com/jaywalnut310/vits/files/9832676/output8.zip)

**Comment by Hemiptelea** [comment]
> Hello, I am currently learning data in Korean. vits can't pronounce properly even though it's 100 epochs. Will the results change if I continue to learn more?
> 
> Here is my learning results.
> 
> KSS: [단순하게 살아라, 현대인은 쓸데없는 절차와 일 때문에 얼마나 복잡한 삶을 살아가는가?]
> [output8.zip](https://github.com/jaywalnut310/vits/files/9832676/output8.zip)
> 


혹시 이 현상 해결 하셨을까요?

**Comment by ORI-Muchim** [comment]
> > Hello, I am currently learning data in Korean. vits can't pronounce properly even though it's 100 epochs. Will the results change if I continue to learn more?
> > 
> > Here is my learning results.
> > 
> > KSS: [단순하게 살아라, 현대인은 쓸데없는 절차와 일 때문에 얼마나 복잡한 삶을 살아가는가?]
> > [output8.zip](https://github.com/jaywalnut310/vits/files/9832676/output8.zip)
> > 
> 
> 
> 혹시 이 현상 해결 하셨을까요?

안녕하세요. 문제 해결했습니다. 공식 레포에 /text 폴더 안에는 한국어를 위한 클리너 파일이 존재하지 않습니다. (https://github.com/CjangCjengh/vits) 이 레포로 가셔서 readme.md 읽어보시면 /text/symbol.py 파일이 있는데 그것을 수정해주셔서야 합니다. 감사합니다!

**Comment by Hemiptelea** [comment]
> 수정해주셔서야

답변담사합니다!

이미 클리너와 심볼이 있는 상태로 학습중이었는데 목소리는 비슷하게 나오지만 한국어를 전혀 구사못해서 질문드린건데 알고보니 학습이 충분히 진행되지 않은상태여서 그런거였습니다.

좋은하루 보내세요!
